import httpx
from urllib.parse import urlencode
from config import (
    FRONTEND_URL,
)
import os

SCOPES = "https://www.googleapis.com/auth/youtube.upload"

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
GOOGLE_REDIRECT_URI = os.getenv(
    "GOOGLE_REDIRECT_URI",
    "https://slide2video.valueupdate.net/youtube/callback"
)


def get_auth_url(state: str) -> str:
    params = {
        "client_id": GOOGLE_CLIENT_ID,
        "redirect_uri": GOOGLE_REDIRECT_URI,
        "response_type": "code",
        "scope": SCOPES,
        "access_type": "online",
        "state": state,
        "prompt": "select_account",
    }
    return "https://accounts.google.com/o/oauth2/v2/auth?" + urlencode(params)


async def exchange_code(code: str) -> str:
    """認証コードをアクセストークンに交換（サーバーには保存しない）"""
    async with httpx.AsyncClient() as client:
        r = await client.post(
            "https://oauth2.googleapis.com/token",
            data={
                "code": code,
                "client_id": GOOGLE_CLIENT_ID,
                "client_secret": GOOGLE_CLIENT_SECRET,
                "redirect_uri": GOOGLE_REDIRECT_URI,
                "grant_type": "authorization_code",
            },
        )
        r.raise_for_status()
        return r.json()["access_token"]


async def upload_video(access_token: str, video_path: str, title: str) -> str:
    """動画を YouTube に非公開でアップロードし、動画IDを返す"""
    metadata = {
        "snippet": {
            "title": title,
            "description": "Generated by Slide2Video (https://slide2video.valueupdate.net)",
        },
        "status": {"privacyStatus": "private"},
    }
    async with httpx.AsyncClient(timeout=300) as client:
        init_r = await client.post(
            "https://www.googleapis.com/upload/youtube/v3/videos"
            "?uploadType=resumable&part=snippet,status",
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "application/json",
                "X-Upload-Content-Type": "video/mp4",
            },
            json=metadata,
        )
        init_r.raise_for_status()
        upload_url = init_r.headers["Location"]

        with open(video_path, "rb") as f:
            data = f.read()
        upload_r = await client.put(
            upload_url,
            headers={
                "Content-Type": "video/mp4",
                "Content-Length": str(len(data)),
            },
            content=data,
        )
        upload_r.raise_for_status()
        return upload_r.json()["id"]
